--- #YAML:1.0
name:         IPC-Locker
version:      1.500
version_from: lib/IPC/Locker.pm
abstract:     Distributed lock handler
license:      perl
installdirs:  site
author:
    - Wilson Snyder <wsnyder@wsnyder.org>
resources:
    homepage: https://www.veripool.org/ipc-locke
    bugtracker: https://www.veripool.org/ipc-locker
requires:
    Net::Domain:                   0
    Pod::Usage:                    1.34
    Test::More:                    0
    Time::HiRes:                   0

meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
distribution_type: module
generated_by: hand
