#!/bin/sh
# $Id$
# DESCRIPTION: Sample file to place in /etc/init.d to start the daemon
# Distributed with IPC::Locker
#
# Copyright 1999-2003 by Wilson Snyder.  This program is free software;
# you can redistribute it and/or modify it under the terms of either the GNU
# General Public License or the Perl Artistic License.
#
# chkconfig: 23456 99 10
# description: Pidstatd provides process information services for IPC::PidStat
# processname: pidstatd

state=$1
prog=/usr/local/bin/pidstatd

case $state in
  start)
	if [ $EUID != 0 ]; then
	    echo "Run as root, only root can do kill 0's"  
	    exit 10
	fi
	if [ -f $prog ] ; then
            echo starting $prog
	    $prog &
	fi
	exit 0
        ;;
  stop)
        if test "x`pidof -o $$ -o $PPID -x pidstatd`" != x; then
                echo -n $"Stopping pidstatd: "
                kill `pidof -o $$ -o $PPID -x pidstatd`
                echo
        fi
	exit 0
        ;;
  restart|reload)
	$0 stop
	$0 start
	exit 0
	;;
  status)
        if test "x`pidof -o $$ -o $PPID -x pidstatd`" != x; then
  	        ps f -ww `pidof -o $$ -o $PPID -x pidstatd`
        fi
	exit 0
	;;
*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
